project_id = "txiwvjfdlxgwjtaibbpb"

[functions.notify-payment-proof]
verify_jwt = true

[functions.create-order]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.create-xendit-payment]
verify_jwt = false

[functions.xendit-webhook]
verify_jwt = false

[functions.get-xendit-payment-status]
verify_jwt = true

[functions.get-resend-emails]
verify_jwt = false

[functions.get-resend-email]
verify_jwt = false

[functions.fetch-facebook-posts]
verify_jwt = true

[functions.get-pending-order]
verify_jwt = false

[functions.upload-order-proof]
verify_jwt = false
