project_id = "mcvnceiugqyvgfmgnizf"

[functions.create-order]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.send-otp]
verify_jwt = true

[functions.verify-otp]
verify_jwt = true
