// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_PUBLIC_KEY ||
  import.meta.env.VITE_SUPABASE_KEY;

export const SUPABASE_CONFIG_ERROR =
  !SUPABASE_URL || !SUPABASE_KEY
    ? 'Missing Supabase environment variables. Please check your build-time env and ensure VITE_SUPABASE_URL and one of VITE_SUPABASE_PUBLISHABLE_KEY / VITE_SUPABASE_ANON_KEY are set.'
    : null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const throwingClient = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get() {
    throw new Error(SUPABASE_CONFIG_ERROR ?? 'Supabase is not configured.');
  },
});

export const supabase: ReturnType<typeof createClient<Database>> = SUPABASE_CONFIG_ERROR
  ? throwingClient
  : createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });